(uiop:define-package :advent/src/package
  (:use-reexport
   :advent/src/day-1
   :advent/src/day-2
   :advent/src/day-3
   :advent/src/day-4
   :advent/src/day-5
   :advent/src/day-6
   :advent/src/day-7
   :advent/src/day-8
   :advent/src/day-9
   :advent/src/day-10
   :advent/src/day-11
   :advent/src/day-12
   :advent/src/day-13
   :advent/src/day-14
   :advent/src/day-15
   :advent/src/day-16
   :advent/src/day-17
   :advent/src/day-18
   :advent/src/day-19
   :advent/src/day-20
   :advent/src/day-21))
